In [1]:
print("hello")

hello

In [2]:
import pandas as pd
import numpy as np
from pathlib import Path

In [35]:
PROJECT_ROOT = Path.cwd().parent
RAW_PATH = PROJECT_ROOT / "data" / "raw"

customers = pd.read_csv(RAW_PATH / "customers.csv")
invoice_items = pd.read_csv(RAW_PATH / "invoice_items.csv")
products = pd.read_csv(RAW_PATH / "products.csv")
purchases = pd.read_csv(RAW_PATH / "purchases.csv")

In [5]:
datasets = {
    "customers": customers,
    "invoice_items": invoice_items,
    "products": products,
    "purchases": purchases
}

for name, data in datasets.items():
    print(f"\n{'=' * 50}")
    print(name)
    print("Shape:", data.shape)
    print("Columns:", data.columns.tolist())
    print("Duplicates:", data.duplicated().sum())
    print("Missing values:", data.isnull().sum().sum())

==================================================
customers
Shape: (8237, 2)
Columns: ['CustomerID', 'customer_type']
Duplicates: 0
Missing values: 0

==================================================
invoice_items
Shape: (436689, 5)
Columns: ['InvoiceID', 'product_id', 'quantity', 'price', 'line_total']
Duplicates: 5426
Missing values: 0

==================================================
products
Shape: (4033, 4)
Columns: ['product_id', 'item', 'category', 'price']
Duplicates: 0
Missing values: 0

==================================================
purchases
Shape: (436689, 5)
Columns: ['InvoiceID', 'date', 'CustomerID', 'product_id', 'quantity']
Duplicates: 5516
Missing values: 0

In [32]:
customers.head()

   CustomerID customer_type
0       17850    wholesaler
1       13047    wholesaler
2       12583    wholesaler
3       13748       private
4       15100       private

In [33]:
invoice_items.head()

   InvoiceID  product_id  quantity  price  line_total  calculated_total
0     536365        3851         6   2.55       15.30             15.30
1     536365        3859         6   3.39       20.34             20.34
2     536365         885         8   2.75       22.00             22.00
3     536365        1873         6   3.39       20.34             20.34
4     536365        2871         6   3.39       20.34             20.34

In [34]:
products.head()

,product_id,item,category,price
0,3851,white hanging heart t-light holder,Home Decor,2.55
1,3859,white metal lantern,Home Decor,3.39
2,885,cream cupid hearts coat hanger,"Health, Beauty & Personal Care",2.75
3,1873,knitted union flag hot water bottle,Party & Festive,3.39
4,2871,red woolly hottie white heart.,"Health, Beauty & Personal Care",3.39

In [31]:
purchases.head()

   InvoiceID       date  CustomerID  product_id  quantity
0     536365 2014-12-01       17850        3851         6
1     536365 2014-12-01       17850        3859         6
2     536365 2014-12-01       17850         885         8
3     536365 2014-12-01       17850        1873         6
4     536365 2014-12-01       17850        2871         6

In [6]:
for name, data in datasets.items():

    print("\n" + "=" * 60)
    print(name.upper())

    numerical_columns = data.select_dtypes(
        include=np.number
    ).columns

    print(data[numerical_columns].describe().T)

============================================================
CUSTOMERS
             count         mean          std     min     25%      50%  \
CustomerID  8237.0  9480.631783  6316.159696  1000.0  3118.0  12618.0

                75%      max
CustomerID  15449.0  18287.0

============================================================
INVOICE_ITEMS
               count           mean            std  min        25%        50%  \
InvoiceID   436689.0  511514.110834  157823.706391  1.0  545589.00  559545.00
product_id  436689.0    2109.265131    1137.512313  1.0    1171.00    2093.00
quantity    436689.0      12.087628     172.252472  1.0       2.00       4.00
price       436689.0       3.226770      21.111450  0.0       1.25       2.08
line_total  436689.0      21.374055     295.049213  0.0       4.68      10.76

                  75%        max
InvoiceID   571229.00  581587.00
product_id    3062.00    4033.00
quantity        12.00   80995.00
price            3.75    8142.75
line_total      18.99  168469.60

============================================================
PRODUCTS
             count         mean          std    min      25%     50%      75%  \
product_id  4033.0  2017.000000  1164.371146  1.000  1009.00  2017.0  3025.00
price       4033.0     3.798143    13.059295  0.001     1.25     2.1     4.15

               max
product_id  4033.0
price        649.5

============================================================
PURCHASES
               count           mean            std     min       25%  \
InvoiceID   436689.0  511514.110834  157823.706391     1.0  545589.0
CustomerID  436689.0   14203.268795    3874.517869  1000.0   13384.0
product_id  436689.0    2109.265131    1137.512313     1.0    1171.0
quantity    436689.0      12.087628     172.252472     1.0       2.0

                 50%       75%       max
InvoiceID   559545.0  571229.0  581587.0
CustomerID   14911.0   16705.0   18287.0
product_id    2093.0    3062.0    4033.0
quantity         4.0      12.0   80995.0

In [7]:
for name, data in datasets.items():

    print("\n" + "=" * 60)
    print(name.upper())

    for column in data.columns:
        print(
            f"{column}: {data[column].nunique()} unique values"
        )

============================================================
CUSTOMERS
CustomerID: 8237 unique values
customer_type: 2 unique values

============================================================
INVOICE_ITEMS
InvoiceID: 33499 unique values
product_id: 4033 unique values
quantity: 302 unique values
price: 548 unique values
line_total: 3177 unique values

============================================================
PRODUCTS
product_id: 4033 unique values
item: 4033 unique values
category: 25 unique values
price: 281 unique values

============================================================
PURCHASES
InvoiceID: 33499 unique values
date: 728 unique values
CustomerID: 8237 unique values
product_id: 4033 unique values
quantity: 302 unique values

In [8]:
print("Customers:")
print("CustomerID unique:", customers["CustomerID"].nunique())
print("CustomerID duplicates:", customers["CustomerID"].duplicated().sum())

print("\nProducts:")
print("product_id unique:", products["product_id"].nunique())
print("product_id duplicates:", products["product_id"].duplicated().sum())

print("\nPurchases:")
print("InvoiceID unique:", purchases["InvoiceID"].nunique())
print("InvoiceID + product_id duplicates:",
      purchases[["InvoiceID", "product_id"]].duplicated().sum())

print("\nInvoice Items:")
print("InvoiceID unique:", invoice_items["InvoiceID"].nunique())
print("InvoiceID + product_id duplicates:",
      invoice_items[["InvoiceID", "product_id"]].duplicated().sum())

Customers:
CustomerID unique: 8237
CustomerID duplicates: 0

Products:
product_id unique: 4033
product_id duplicates: 0

Purchases:
InvoiceID unique: 33499
InvoiceID + product_id duplicates: 10988

Invoice Items:
InvoiceID unique: 33499
InvoiceID + product_id duplicates: 10988

In [9]:
purchases["date"] = pd.to_datetime(
    purchases["date"],
    errors="coerce"
)

print("Invalid dates:", purchases["date"].isna().sum())
print("First date:", purchases["date"].min())
print("Last date:", purchases["date"].max())
print("Unique dates:", purchases["date"].nunique())

Invalid dates: 0
First date: 2014-01-01 00:00:00
Last date: 2015-12-30 00:00:00
Unique dates: 728

In [10]:
print("Purchase quantity < 0:")
print((purchases["quantity"] < 0).sum())

print("\nInvoice quantity < 0:")
print((invoice_items["quantity"] < 0).sum())

print("\nPrice < 0:")
print((invoice_items["price"] < 0).sum())

print("\nLine total < 0:")
print((invoice_items["line_total"] < 0).sum())

Purchase quantity < 0:
0

Invoice quantity < 0:
0

Price < 0:
0

Line total < 0:
0

In [11]:
print("Top quantities:")
print(
    purchases
    .sort_values("quantity", ascending=False)
    [["InvoiceID", "date", "CustomerID", "product_id", "quantity"]]
    .head(20)
)

Top quantities:
        InvoiceID       date  CustomerID  product_id  quantity
397451     581483 2015-12-09       16446        2414     80995
37126      541431 2015-01-18       12346        2074     74215
370473     578841 2015-11-25       13256         239     12540
308128     573008 2015-10-27       12901        3941      4800
143243     554868 2015-05-27       13135        3393      4300
61586      544612 2015-02-22       18087        1159      3906
188812     560599 2015-07-19       14609        1193      3186
109624     550461 2015-04-18       15749        1198      3114
32732      540815 2015-01-11       15749        1198      3114
318104     573995 2015-11-02       16308        3365      3000
3670       536830 2014-12-02       16754        3941      2880
204041     562439 2015-08-04       12931         209      2880
139695     554272 2015-05-23       12901        2361      2700
49734      543057 2015-02-03       16333        3941      2592
54330      543669 2015-02-11       16029        1581      2400
21714      539101 2014-12-16       16029        1581      2400
308097     573003 2015-10-27       14646        2762      2400
57506      544152 2015-02-16       14609        1193      2400
82267      547037 2015-03-20       14101        2335      2160
320908     574294 2015-11-03       16333        2787      2100

In [12]:
print("Top prices:")
print(
    invoice_items
    .sort_values("price", ascending=False)
    [["InvoiceID", "product_id", "quantity", "price", "line_total"]]
    .head(20)
)

Top prices:
        InvoiceID  product_id  quantity    price  line_total
118352     551697        2711         1  8142.75     8142.75
308822     573077        2061         1  4161.06     4161.06
308846     573080        2061         1  4161.06     4161.06
295254     571751        2061         1  3949.32     3949.32
269591     569382        2061         1  3155.95     3155.95
208732     562946        2061         1  2500.00     2500.00
97061      548813        2061         1  2382.92     2382.92
295255     571751        2061         1  2118.74     2118.74
97064      548820        2061         1  2053.07     2053.07
244129     566927        2061         1  2033.10     2033.10
101491     549468        2061         1  1867.86     1867.86
76240      546328        2061         1  1687.17     1687.17
76241      546329        2061         1  1687.17     1687.17
389990     580727        1074         1  1599.26     1599.26
375623     579196        1074         1  1526.76     1526.76
344551     576339        1074         1  1500.36     1500.36
365335     578270        1074         1  1270.06     1270.06
97063      548813        2061         1  1252.95     1252.95
139314     554155        2061         1  1241.98     1241.98
139991     554301        2061         1  1241.98     1241.98

In [13]:
print("Top line totals:")
print(
    invoice_items
    .sort_values("line_total", ascending=False)
    [["InvoiceID", "product_id", "quantity", "price", "line_total"]]
    .head(20)
)

Top line totals:
        InvoiceID  product_id  quantity    price  line_total
397451     581483        2414     80995     2.08   168469.60
37126      541431        2074     74215     1.04    77183.60
155418     556444        2494        60   649.50    38970.00
118352     551697        2711         1  8142.75     8142.75
248706     567423        3218      1412     5.06     7144.72
32732      540815        1198      3114     2.10     6539.40
109624     550461        1198      3114     2.10     6539.40
308097     573003        2762      2400     2.08     4992.00
32730      540815        3851      1930     2.55     4921.50
109620     550461        3851      1930     2.40     4632.00
32793      540818        1049       670     6.75     4522.50
171574     558526        2886       540     8.15     4401.00
109622     550461        1049       670     6.35     4254.50
204041     562439         209      2880     1.45     4176.00
308822     573077        2061         1  4161.06     4161.06
308846     573080        2061         1  4161.06     4161.06
32189      540689        1665      1284     3.21     4121.64
295254     571751        2061         1  3949.32     3949.32
393298     581115        2095      1404     2.75     3861.00
10797      537659        3767       600     6.38     3828.00

In [14]:
invoice_items["calculated_total"] = (
    invoice_items["quantity"] * invoice_items["price"]
)

print(
    "Line total mismatches:",
    (
        ~np.isclose(
            invoice_items["line_total"],
            invoice_items["calculated_total"],
            rtol=0.01
        )
    ).sum()
)

Line total mismatches: 0

In [15]:
purchase_customers = set(purchases["CustomerID"])
customer_ids = set(customers["CustomerID"])

missing_customers = purchase_customers - customer_ids

print("CustomerIDs in purchases:", len(purchase_customers))
print("CustomerIDs in customers:", len(customer_ids))
print("Missing CustomerIDs:", len(missing_customers))

CustomerIDs in purchases: 8237
CustomerIDs in customers: 8237
Missing CustomerIDs: 0

In [16]:
purchase_products = set(purchases["product_id"])
product_ids = set(products["product_id"])

missing_products_purchase = purchase_products - product_ids

print("ProductIDs in purchases:", len(purchase_products))
print("ProductIDs in products:", len(product_ids))
print("Missing ProductIDs:", len(missing_products_purchase))

ProductIDs in purchases: 4033
ProductIDs in products: 4033
Missing ProductIDs: 0

In [17]:
invoice_products = set(invoice_items["product_id"])

missing_products_invoice = invoice_products - product_ids

print(
    "Missing ProductIDs in invoice_items:",
    len(missing_products_invoice)
)

Missing ProductIDs in invoice_items: 0

In [18]:
purchase_invoices = set(purchases["InvoiceID"])
invoice_item_invoices = set(invoice_items["InvoiceID"])

missing_invoices = invoice_item_invoices - purchase_invoices

print("Invoices in purchases:", len(purchase_invoices))
print("Invoices in invoice_items:", len(invoice_item_invoices))
print("Missing invoices:", len(missing_invoices))

Invoices in purchases: 33499
Invoices in invoice_items: 33499
Missing invoices: 0

In [19]:
purchase_qty = (
    purchases
    .groupby(["InvoiceID", "product_id"])["quantity"]
    .sum()
    .reset_index(name="purchase_quantity")
)

invoice_qty = (
    invoice_items
    .groupby(["InvoiceID", "product_id"])["quantity"]
    .sum()
    .reset_index(name="invoice_quantity")
)

In [20]:
quantity_check = purchase_qty.merge(
    invoice_qty,
    on=["InvoiceID", "product_id"],
    how="outer"
)

In [21]:
print(
    "Missing in purchases:",
    quantity_check["purchase_quantity"].isna().sum()
)

print(
    "Missing in invoice_items:",
    quantity_check["invoice_quantity"].isna().sum()
)

Missing in purchases: 0
Missing in invoice_items: 0

In [22]:
purchase_invoices = set(purchases["InvoiceID"])
invoice_item_invoices = set(invoice_items["InvoiceID"])

missing_invoices = invoice_item_invoices - purchase_invoices

print("Invoices in purchases:", len(purchase_invoices))
print("Invoices in invoice_items:", len(invoice_item_invoices))
print("Missing invoices:", len(missing_invoices))

Invoices in purchases: 33499
Invoices in invoice_items: 33499
Missing invoices: 0

In [23]:
purchase_qty = (
    purchases
    .groupby(["InvoiceID", "product_id"])["quantity"]
    .sum()
    .reset_index(name="purchase_quantity")
)

invoice_qty = (
    invoice_items
    .groupby(["InvoiceID", "product_id"])["quantity"]
    .sum()
    .reset_index(name="invoice_quantity")
)

In [24]:
quantity_check = purchase_qty.merge(
    invoice_qty,
    on=["InvoiceID", "product_id"],
    how="outer"
)

In [25]:
print(
    "Missing in purchases:",
    quantity_check["purchase_quantity"].isna().sum()
)

print(
    "Missing in invoice_items:",
    quantity_check["invoice_quantity"].isna().sum()
)

Missing in purchases: 0
Missing in invoice_items: 0

In [26]:
quantity_check["quantity_match"] = np.isclose(
    quantity_check["purchase_quantity"].fillna(0),
    quantity_check["invoice_quantity"].fillna(0)
)

print(
    "Quantity mismatches:",
    (~quantity_check["quantity_match"]).sum()
)

Quantity mismatches: 0

In [27]:
product_consistency = (
    products
    .groupby("product_id")
    .agg({
        "item": "nunique",
        "category": "nunique",
        "price": "nunique"
    })
)

print(product_consistency.max())

item        1
category    1
price       1
dtype: int64

In [28]:
print("=" * 60)
print("STEP 2 — DATA VALIDATION SUMMARY")
print("=" * 60)

print("\nCustomers:")
print("Rows:", len(customers))
print("Duplicate rows:", customers.duplicated().sum())
print("Duplicate CustomerIDs:", customers["CustomerID"].duplicated().sum())

print("\nProducts:")
print("Rows:", len(products))
print("Duplicate rows:", products.duplicated().sum())
print("Duplicate product IDs:", products["product_id"].duplicated().sum())

print("\nPurchases:")
print("Rows:", len(purchases))
print("Duplicate rows:", purchases.duplicated().sum())

print("\nInvoice Items:")
print("Rows:", len(invoice_items))
print("Duplicate rows:", invoice_items.duplicated().sum())

print("\nRelationships:")
print("Missing CustomerIDs:", len(missing_customers))
print("Missing ProductIDs in purchases:", len(missing_products_purchase))
print("Missing ProductIDs in invoice_items:", len(missing_products_invoice))
print("Missing InvoiceIDs:", len(missing_invoices))
print("Quantity mismatches:", (~quantity_check["quantity_match"]).sum())

print("\nDates:")
print("Start:", purchases["date"].min())
print("End:", purchases["date"].max())
print("Unique dates:", purchases["date"].nunique())

print("\nNegative values:")
print("Negative purchase quantity:", (purchases["quantity"] < 0).sum())
print("Negative invoice quantity:", (invoice_items["quantity"] < 0).sum())
print("Negative price:", (invoice_items["price"] < 0).sum())
print("Negative line total:", (invoice_items["line_total"] < 0).sum())

============================================================
STEP 2 — DATA VALIDATION SUMMARY
============================================================

Customers:
Rows: 8237
Duplicate rows: 0
Duplicate CustomerIDs: 0

Products:
Rows: 4033
Duplicate rows: 0
Duplicate product IDs: 0

Purchases:
Rows: 436689
Duplicate rows: 5516

Invoice Items:
Rows: 436689
Duplicate rows: 5426

Relationships:
Missing CustomerIDs: 0
Missing ProductIDs in purchases: 0
Missing ProductIDs in invoice_items: 0
Missing InvoiceIDs: 0
Quantity mismatches: 0

Dates:
Start: 2014-01-01 00:00:00
End: 2015-12-30 00:00:00
Unique dates: 728

Negative values:
Negative purchase quantity: 0
Negative invoice quantity: 0
Negative price: 0
Negative line total: 0